### PR TITLE
Update README and JSON samples

### PR DESCRIPTION
**Pull request by rafaelfolco**
Updated README with sample json and usage
Removed deprecated go code and tests
Placed input and output json in JSON dir

### CODE REVIEW

**Review by k-rister — COMMENTED** [review]
I'm not sure I see the need to preserve the old stuff in the dev directory.   Also, I think having a couple examples is probably a good idea but I think they should relatively simple -- its too hard to comprehend what is going on if the output is several pages.

**Comment by rafaelfolco** [comment]
> I'm not sure I see the need to preserve the old stuff in the dev directory. Also, I think having a couple examples is probably a good idea but I think they should relatively simple -- its too hard to comprehend what is going on if the output is several pages.

Ok, I was unsure we could simply remove go code and the testing dir. I was thinking in migrating the tests to python, then delete. Regarding samples, I'm going to dry the mv json so it becomes much simpler and we could view it in one page.

**Comment by k-rister** [comment]
> Ok, I was unsure we could simply remove go code and the testing dir. I was thinking in migrating the tests to python, then delete. Regarding samples, I'm going to dry the mv json so it becomes much simpler and we could view it in one page.

I think we are in a unique position with multiplex.  Despite there having been a lot of work already done here it is almost completely unused.  This means we can make drastic changes with little impact to our existing work.  So I think in this situation there may not be a lot of value to the old stuff depending on how big our changes are going to be.

I'm not even sure how applicable the old tests are given all the changes that have been made to the schema and design of how it works.

One other thing to consider is how these tests are going to run.  Is it simply going to check return codes or is this going to be a more unit-test like where it compares the output that is generated to an expected output file (diff)?  While the comparison is probably a more strenuous test I fear that it will create the exact scenario we were hoping to avoid where every time a change is made the output will change so the expected output files have to be updated.  Since the whole point of this project is to take some input and then generate some (valid) output there probably won't be many reasons to be making changes unless it is changing the output.  If that is the case I fear that the change author just takes the output they are generating and makes it the new expected output so the test will always pass which makes it kinda useless.

**Comment by rafaelfolco** [comment]
I converted this in a new PR https://github.com/perftool-incubator/multiplex/pull/16

**Pull request closed without merging**
